const gameDOM = document.getElementById('game-wrapper')
const scoreDOM = document.getElementById('score')
const weaponDOM = document.getElementById('weapon')
const lvlDOM = document.getElementById('level')
const zbLeftDOM = document.getElementById('zombies-left')
const goalsDOM = document.getElementById('goals')
const notifDOM = document.getElementById('notification')
